path: /Users/reena/Downloads/archive
train: /Users/reena/Downloads/archive/raw_data/public_training_set_release_2.0
val: /Users/reena/Downloads/archive/raw_data/public_validation_set_2.0

# classes
names:
  0: food